package me.zort.iis.server.iisserver.domain.access;

public enum Privilege {
    MANAGE_USERS,
    MANAGE_THEMES,
    MANAGE_CAMPAIGNS,
    MANAGE_STEPS,
    MANAGE_ACTIVITIES,
    VIEW_ASSIGNED_CAMPAIGNS,
    VIEW_ASSIGNED_STEPS,
    VIEW_ASSIGNED_ACTIVITIES,
    VIEW_AVAILABLE_ACTIVITIES

}
